takahirom/roborazzi

roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/capture.kt

Fix https://github.com/takahirom/roborazzi/issues/4

Add changeThreshold for verification

---

roborazzi/src/main/java/com/github/takahirom/roborazzi/capture.kt

Change default threshold for verify task

---

.github/workflows/create-golden-test.yaml
.github/workflows/get-diff-test.yaml
.github/workflows/test.yaml
app/src/main/res/values/strings.xml

Can be used as a example and for testing of roborazzi

Add diff test

---

app/src/test/java/com/github/takahirom/roborazzi/sample/ManualTest.kt
roborazzi-painter/src/main/java/com/github/takahirom/roborazzi/AnimatedGifEncoder.kt
roborazzi-painter/src/main/java/com/github/takahirom/roborazzi/RoboCanvas.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/capture.kt

Fix https://github.com/takahirom/roborazzi/issues/11

Screenshot image size can now be adjusted

---

app/src/test/java/com/github/takahirom/roborazzi/sample/ManualTest.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/CompareReportResult.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/capture.kt

This will be a 1.1 feature.
step 1 to do https://github.com/takahirom/roborazzi/issues/24

Add result json writer to compare

---

.github/workflows/get-diff-test.yaml
.github/workflows/test.yaml
README.md
roborazzi-core/src/main/java/io/github/takahirom/roborazzi/CompareReportCaptureResult.kt
roborazzi-core/src/main/java/io/github/takahirom/roborazzi/CompareReportResult.kt
roborazzi-core/src/main/java/io/github/takahirom/roborazzi/RoborazziReportConst.kt
roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt

This will be a 1.1 feature.
step 3 to do https://github.com/takahirom/roborazzi/issues/24

Add verification task

---

gradle.properties
roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt

Fix https://github.com/takahirom/roborazzi/issues/30

Adapt to configuration cache

---

README.md
roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/capture.kt

https://github.com/takahirom/roborazzi/issues/23

Fail test when verification detects changes

---

.github/workflows/get-diff-test.yaml
app/src/main/res/values/strings.xml
app/src/main/res/values/strings_for_test.xml
app/src/test/java/com/github/takahirom/roborazzi/sample/ManualTest.kt
roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt

Fix https://github.com/takahirom/roborazzi/issues/23

Fix ensure verify function runs correctly

---

README.md

https://github.com/takahirom/roborazzi/issues/43

Add documentation of GitHub Actions

---

README.md
app/build.gradle
app/src/test/java/com/github/takahirom/roborazzi/sample/ManualTest.kt
roborazzi/build.gradle
roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt

Fix https://github.com/takahirom/roborazzi/issues/33

Support View, Compose lambda, Bitmap

---

roborazzi/src/main/AndroidManifest.xml
roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/RoborazziTransparentActivity.kt
roborazzi/src/main/res/values/themes.xml

Fix https://github.com/takahirom/roborazzi/issues/67

Use transparent theme for compose lambda

---

app/src/test/java/com/github/takahirom/roborazzi/sample/RuleTestWithAllImage.kt
roborazzi-junit-rule/src/main/java/com/github/takahirom/roborazzi/RoborazziRule.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/DefaultFileNameGenerator.kt

Fix https://github.com/takahirom/roborazzi/issues/66

Add RoborazziRule.Options.outputFileProvider

---

.github/workflows/CompareScreenshotComment.yml

Checked by
```
brew install shellcheck
brew install actionlint
actionlint .github/workflows/*
```

Fix shellcheck problems

---

roborazzi/build.gradle

Add dependencies version name to roborazzi-core

---

roborazzi-compose/build.gradle
roborazzi-compose/src/main/java/com/github/takahirom/roborazzi/RoborazziCompose.kt

Add workaround for Unable to resolve activity for Intent

---

app/src/test/java/com/github/takahirom/roborazzi/sample/RuleTestWithPath.kt
roborazzi-junit-rule/src/main/java/com/github/takahirom/roborazzi/RoborazziRule.kt

https://github.com/takahirom/roborazzi/issues/106

Use CaptureType.None as the default option for RoborazziRule

---

app-without-compose/build.gradle
app/build.gradle
app/src/test/java/com/github/takahirom/roborazzi/sample/Sdk25DontWorkScreenshotTest.kt
roborazzi-compose/build.gradle
roborazzi/build.gradle
roborazzi/src/main/java/com/github/takahirom/roborazzi/ViewScreenshot.kt

Fix https://github.com/takahirom/roborazzi/issues/114

Add warning that the config under SDK 26 may not function properly and update Robolectric

---

include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt
include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt
include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt

Fix https://github.com/takahirom/roborazzi/issues/97

Fix issue test task is skippped unexpectedly

---

include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt
include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt
include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt

https://github.com/takahirom/roborazzi/issues/117#issuecomment-1629907657

Fix issue system properties take precedence over gradle task

---

include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt
include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt

https://github.com/takahirom/roborazzi/issues/117#issuecomment-1629907657

Generate compare report even if we use system property

---

include-build/roborazzi-gradle-plugin/build.gradle
include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt
roborazzi-compose-desktop/build.gradle
sample-compose-desktop-multiplatform/build.gradle.kts

Fix the issue where Roborazzi changes the timing of the configuration

---

include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/CaptureResult.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/CaptureResults.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/CompareReportResult.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/ResultSummary.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziReportConst.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/processOutputImageAndReport.kt
include-build/roborazzi-core/src/jvmTest/kotlin/io/github/takahirom/roborazzi/CaptureResultTest.kt
include-build/roborazzi-core/src/jvmTest/kotlin/io/github/takahirom/roborazzi/CompareReportResultTest.kt
include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt
include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt
include-build/roborazzi-gradle-plugin/src/integrationTest/projects/gradle.properties
include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt
roborazzi-compose-desktop/src/commonMain/kotlin/io/github/takahirom/roborazzi/RoborazziDesktop.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt

Preparation for https://github.com/takahirom/roborazzi/issues/153

Refactor results json

---

include-build/roborazzi-core/build.gradle
include-build/roborazzi-gradle-plugin/build.gradle
roborazzi-compose-desktop/build.gradle

https://ossindex.sonatype.org/vulnerability/CVE-2022-45688?component-type=maven&component-name=org.json%2Fjson&utm_source=ossindex-client&utm_medium=integration&utm_content=1.7.0

Update json library to fix vulnerabilities

---

include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/processOutputImageAndReport.kt

The current reporter structure is tightly coupled with the "Compare" functionality. As the reporter is now intended to be used for various other purposes, it needs to be refactored for improved modularity and extensibility.

Refactor reporter in RoborazziOptions

---

README.md
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/fileWithOutputDirectoryContext.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/fileWithRecordFilePathStrategy.kt
include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt
include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt
include-build/roborazzi-gradle-plugin/src/integrationTest/projects/app/src/test/java/com/github/takahirom/integration_test_project/RoborazziTest.kt
roborazzi-compose-desktop/src/commonMain/kotlin/io/github/takahirom/roborazzi/RoborazziDesktop.kt
roborazzi-compose/src/main/java/com/github/takahirom/roborazzi/RoborazziCompose.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt
sample-android/src/test/java/com/github/takahirom/roborazzi/sample/RuleTestWithPath.kt

close https://github.com/takahirom/roborazzi/issues/171

Add roborazzi.record.filePathStrategy gradle.properties property for dynamic output path resolution

---

include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt
include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt
include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt

Fix https://github.com/takahirom/roborazzi/issues/174

Resolve the FileNotFoundException Issue with RoborazziPlugin

---

include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoboCanvas.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/processOutputImageAndReport.kt
roborazzi-painter/src/main/java/com/github/takahirom/roborazzi/AwtRoboCanvas.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt

Make Roborazzi's ImageComparator customizable

---

include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt

Fix https://github.com/takahirom/roborazzi/issues/180

Set Default Value of CompareOptions.changeThreshold to Zero

---

roborazzi-compose/src/main/java/com/github/takahirom/roborazzi/RoborazziCompose.kt

Fixed a bug where options set via RoborazziRule were ignored

---

include-build/roborazzi-gradle-plugin/build.gradle
include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt
include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt
include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt

https://github.com/takahirom/roborazzi/issues/188

Fix the issue of keeping the previous test reports

---

include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/DefaultFileNameGenerator.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/roboOutputName.kt
roborazzi-junit-rule/src/main/java/com/github/takahirom/roborazzi/RoborazziRule.kt
sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ManualTest.kt
sample-android/src/test/java/com/github/takahirom/roborazzi/sample/RuleTestWithPath.kt

Enhance Flexibility with Custom File Naming in Roborazzi via roboOutputName() Function

---

roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt

Enhanced window layering in screenshot functionality: Windows are now sorted by type for consistent layering, ensuring dialogs and other important windows are captured correctly.

Improve Window Layering by Sorting Windows by Type

---

gradle/libs.versions.toml

https://ossindex.sonatype.org/vulnerability/CVE-2023-5072

Update the org.json library to patch the vulnerability

---

gradle/libs.versions.toml
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/CaptureResult.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoboCanvas.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/processOutputImageAndReport.kt
include-build/roborazzi-core/src/jvmTest/kotlin/io/github/takahirom/roborazzi/CaptureResultTest.kt
roborazzi-painter/src/main/java/com/github/takahirom/roborazzi/AwtRoboCanvas.kt
sample-android/build.gradle
sample-android/src/main/AndroidManifest.xml
sample-android/src/test/java/com/github/takahirom/roborazzi/sample/boxed/AdditionalDataTest.kt
sample-android/src/test/java/com/github/takahirom/roborazzi/sample/boxed/ContextDataTest.kt

close https://github.com/takahirom/roborazzi/issues/257

Enable adding metadata to image

---

include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt

Add helpful error message for class cast exception

---

README.md
docs/topics/faq.md

close https://github.com/takahirom/roborazzi/issues/255, https://github.com/takahirom/roborazzi/issues/271, https://github.com/takahirom/roborazzi/issues/114#issuecomment-2001897895

Add "The images taken from Roborazzi seem broken" FAQ

---

roborazzi-painter/src/main/java/com/github/takahirom/roborazzi/AwtRoboCanvas.kt

Fix false positive issue in verification of scaled transparent images

---

README.md
docs/topics/faq.md

Add "Why do my screenshot tests fail inconsistently across different operating systems" section

---

gradle/libs.versions.toml
include-build/roborazzi-core/build.gradle
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/CaptureResult.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/CaptureResults.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/ResultSummary.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt
include-build/roborazzi-core/src/jvmTest/kotlin/io/github/takahirom/roborazzi/CaptureResultTest.kt
include-build/roborazzi-gradle-plugin/build.gradle
roborazzi-compose-desktop/build.gradle
sample-android/src/test/java/com/github/takahirom/roborazzi/sample/boxed/ContextDataTest.kt

Migrate json library to kotlinx.serialization since Gson does not support KMM.
Fixes #305

refactor: migrate from Gson to KotlinX.Serialization

---

roborazzi-compose/src/main/java/com/github/takahirom/roborazzi/RoborazziCompose.kt

close https://github.com/takahirom/roborazzi/issues/375

Use the `use` block to prevent leaks

---

README.md
docs/topics/build_setup.md
include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt
include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt
include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt
roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/RoborazziGradleTask.kt

close https://github.com/takahirom/roborazzi/issues/452

Add clear roborazzi task

---

.github/workflows/CompareScreenshot.yml
.github/workflows/StoreScreenshot.yml
roborazzi-compose-ios/src/iosMain/kotlin/io/github/takahirom/roborazzi/RoborazziIos.kt

 Set a classDiscriminator to avoid polymorphic serializer error

---

README.md
docs/topics/preview_support.md

update preview screenshot docs

---

include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt

https://github.com/takahirom/roborazzi/issues/497

Use gradlePropertiesPrefixedBy instead of project.properties for Gradle Isolated Projects

---

README.md
docs/topics/how_to_use.md

Added extra information to README.md on how to configure Differ to address issues caused by antialiasing differences.

Add description how to configure Differ

---

roborazzi-idea-plugin/build.gradle.kts
roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/PreviewViewModel.kt

Fix https://github.com/takahirom/roborazzi/issues/502, https://github.com/takahirom/roborazzi/issues/485, https://github.com/takahirom/roborazzi/issues/467

Fix the issue with the Roborazzi Idea Plugin not being able to display images

---

README.md
docs/topics/compose_multiplatform.md
roborazzi-compose-desktop/build.gradle
roborazzi-compose-desktop/src/commonMain/kotlin/io/github/takahirom/roborazzi/RoborazziDesktop.kt
sample-compose-desktop-jvm/build.gradle.kts
sample-compose-desktop-multiplatform/build.gradle.kts

close https://github.com/takahirom/roborazzi/issues/444

Try to remove context receiver of desktop

---

include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt

Improve AI assertion error message

---

roborazzi-painter/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/DifferBufferedImage.kt
sample-android/src/test/java/com/github/takahirom/roborazzi/sample/boxed/LosslessWebpTest.kt

close https://github.com/takahirom/roborazzi/issues/546

Fix WebP comparison issue with transparent colors

---

roborazzi-compose/src/main/java/com/github/takahirom/roborazzi/RoborazziComposeOptions.kt
sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ComposeLambdaTest.kt

I think it might be confusing if it is compose theme or not.

Rename theme() to activityTheme()

---

roborazzi-painter/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/AwtRoboCanvas.kt

Show diff when size changed

---

include-build/roborazzi-core/src/commonMain/kotlin/com/github/takahirom/roborazzi/AiAssertionOptions.kt
roborazzi-ai-gemini/src/commonMain/kotlin/com/github/takahirom/roborazzi/GeminiRoborazziAi.kt
roborazzi-ai-openai/src/commonMain/kotlin/com/github/takahirom/roborazzi/OpenAiAiAssertionModel.kt
sample-android/src/test/java/com/github/takahirom/roborazzi/sample/boxed/AiManualTest.kt

This feature will be used by https://github.com/takahirom/arbigent

Add multiple image assertion

---

roborazzi-painter/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/AwtRoboCanvas.kt

Fix font crash

---

.github/workflows/test.yaml
gradle/libs.versions.toml
include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt

https://github.com/Kotlin/dokka/issues/2956#issuecomment-2191606810

Downgrade Java target version to 11 and add javadoc generation to CI workflow

---

include-build/roborazzi-core/src/androidMain/kotlin/com/github/takahirom/roborazzi/ViewScreenshot.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt
include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/processOutputImageAndReport.kt
include-build/roborazzi-core/src/commonMain/kotlin/com/github/takahirom/roborazzi/RoborazziProperties.kt
include-build/roborazzi-core/src/commonMain/kotlin/com/github/takahirom/roborazzi/debugLog.kt
roborazzi-ai-gemini/src/commonMain/kotlin/com/github/takahirom/roborazzi/GeminiRoborazziAi.kt
roborazzi-ai-openai/src/commonMain/kotlin/com/github/takahirom/roborazzi/OpenAiAiAssertionModel.kt
roborazzi-painter/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/AwtRoboCanvas.kt
roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt

Rename debugLog to roborazziDebugLog and update usages across the codebase

---

include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/GenerateComposePreviewRobolectricTestsExtension.kt
roborazzi-compose-preview-scanner-support/src/main/java/com/github/takahirom/roborazzi/RoborazziPreviewScannerSupport.kt

close https://github.com/takahirom/roborazzi/issues/662

Add RoborazziComposePreviewTestCategory to preview tests
