README.md, app/src/test/java/com/github/takahirom/roborazzi/sample/ManualTest.kt, app/src/test/java/com/github/takahirom/roborazzi/sample/RuleTest.kt, app/src/test/java/com/github/takahirom/roborazzi/sample/RuleTestWithOnlyFailWithFail.kt, roborazzi-junit-rule/src/main/java/com/github/takahirom/roborazzi/RoborazziRule.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/DefaultFileNameGenerator.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/FileNameCreator.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/capture.kt
Fix https://github.com/takahirom/roborazzi/issues/3
This PR introduces a feature that automatically generates a file name for screenshots taken by Roborazzi. If you don't specify a file name for the screenshot, Roborazzi will use the method name as the file name for you. The format of the file name will be as follows:
build/outputs/roborazzi/com_..._ManualTest_captureRoboImageSample.png
This will make it easier for users to manage and organize their screenshot files without having to manually name each one.
=> Introduce automatic screenshot file naming

app/src/test/java/com/github/takahirom/roborazzi/sample/ManualTest.kt, roborazzi-junit-rule/src/main/java/com/github/takahirom/roborazzi/RoborazziRule.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/capture.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/captureDump.kt
The reason why I'm renaming to RoborazziOptions is that the class is not only for capture but also verify.
=> Rename to RoborazziOptions from CaptureOptions

app/build.gradle, app/src/test/java/com/github/takahirom/roborazzi/sample/ComposeTest.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/ComposeScreenshot.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/ViewScreenshot.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/capture.kt
Not sure about the right API, particularly to support both full screen screenshots, and component screenshots without a crop.
=> Support Wear screenshots

app/src/test/java/com/github/takahirom/roborazzi/sample/ComposeTest.kt, roborazzi-painter/src/main/java/com/github/takahirom/roborazzi/RoboCanvas.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/ComposeScreenshot.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/ViewScreenshot.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/capture.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/captureDump.kt
Fix https://github.com/takahirom/roborazzi/issues/34
Support image pixel type
~Currently, we are using RGB565 for performance reasons. However, transparency can be useful. For now, how about adding an option to use transparency, while leaving the default value as is?~
In this PR, I'm going to change the default image type to ARGB 8888. I'm considering making this the default setting, and I think this feature will be included in version 1.2. The reason is that we are getting more CPU and memory resources as time passes, and even in Android, Glide's default value is ARGB 8888.
https://bumptech.github.io/glide/doc/migrating.html#decodeformat
=> Support image pixel type and make ARGB_8888 the default value.

app/src/test/java/com/github/takahirom/roborazzi/sample/ComposeSetContentTest.kt, app/src/test/java/com/github/takahirom/roborazzi/sample/ManualTest.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt
It seems that ViewTreeObserver.OnGlobalLayoutListener doesn't work when using Compose. So, I tried to use [Snapshot.registerApplyObserver{}](https://dev.to/zachklipp/introduction-to-the-compose-snapshot-system-19cn).
https://github.com/takahirom/roborazzi/pull/16#issuecomment-1525874734
Fix https://github.com/takahirom/roborazzi/issues/39
=> Fix Compose gif

roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt
This PR introduces a new task, verifyAndRecordRoborazzi, which aims to streamline the process of recording and verifying tests into a single run. This approach enhances efficiency, although it may require multiple runs if a single test contains multiple captureRoboImage() calls when the images are changed. Feedback is welcome.
See https://github.com/takahirom/roborazzi/pull/51#issuecomment-1543442519 for more information.
=> Add verifyAndRecordRoborazzi task

.github/workflows/compare-verify-test.yaml, roborazzi/src/main/java/com/github/takahirom/roborazzi/DefaultFileNameGenerator.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/capture.kt
Fix https://github.com/takahirom/roborazzi/issues/80 , https://github.com/takahirom/roborazzi/issues/75
This will constitute a breaking change. The default filename will be altered to something like `com.github.takahirom.roborazzi.sample.ManualTest.captureRoboImageSample.png` from `com_github_takahirom_roborazzi_sample_ManualTest.captureRoboImageSample.png`
You can try it like this.
./gradlew recordRoborazziDebug -Proborazzi.record.resizeScale=0.5 -Proborazzi.record.nameStrategy=testClassAndMethod
or
gradle.properties
```
roborazzi.record.resizeScale=0.25
roborazzi.record.namingStrategy=testClassAndMethod
```
https://github.com/takahirom/roborazzi/pull/84
For compatibility, you can use `escapedTestPackageAndClassAndMethod `. But keep in mind it can be deprecated.
``` …
```
=> Add default options parameters like "roborazzi.record.resizeScale" and "roborazzi.record.namingStrategy"

app/src/test/java/com/github/takahirom/roborazzi/sample/ComposeSetContentTest.kt, app/src/test/java/com/github/takahirom/roborazzi/sample/ComposeTest.kt, app/src/test/java/com/github/takahirom/roborazzi/sample/RuleTest.kt, app/src/test/java/com/github/takahirom/roborazzi/sample/RuleTestWithAllImage.kt, app/src/test/java/com/github/takahirom/roborazzi/sample/RuleTestWithLastImage.kt, app/src/test/java/com/github/takahirom/roborazzi/sample/RuleTestWithPath.kt, build.gradle, roborazzi-junit-rule/src/main/java/com/github/takahirom/roborazzi/RoborazziRule.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/DefaultFileNameGenerator.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/ExperimentalRoborazziApi.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/RoborazziContext.kt
Fix #104 
This PR introduces an API to set the default file path within the Roborazzi context. This enables the client to override the default file path as needed and clear it after use.
This PR also fixes the CaptureType.LastImage behavior. It should not utilize the mechanism for generating GIFs, as this leads to the creation of an excessive number of images.
=> Add support for default file path setting by RoborazziRule and refactor RoborazziRule

.github/workflows/CompareScreenshot.yml, app/src/test/java/com/github/takahirom/roborazzi/sample/RuleTestWithPath.kt, include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt, include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt, include-build/roborazzi-gradle-plugin/src/integrationTest/projects/app/src/test/java/com/github/takahirom/integration_test_project/RoborazziTest.kt, include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/capture.kt
=> Alter the default output directory for comparison images and incorporate outputDirectoryPath into the comparison options

roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt
When taking a screenshot, if `rootComponent.image` is `null`, throw an exception with the message "Does the rendering element exist?" instead of an NPE.
In the implementation of `RoboComponent.image` (View, Compose), both ultimately call `View.fetchImage` to attempt to obtain a bitmap, and the image is null only if the size is less than 0 or the bitmap generation fails. If the cause of the bitmap generation failure (i.e. `bitmapFuture` returning `null`) during screenshot is extremely rare, the user most likely has not placed any rendering elements.
This is not something that can be easily read from the stack trace (for beginners), so I will add a message to inform about it.
This is something I felt would be good to have in roborazzi when I encountered a case where I didn't render anything …
=> Add message in exception if image was not found

include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/CaptureResults.kt, include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/ResultSummary.kt, include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziReportConst.kt
When looking at the html report there is this summary on top and then if you want to see the changed screenshots you have to manually scroll down. 
I thought it could be nice adding some html anchors so when any of these cells of recorded, added, changed or unchanged is clicked the browser goes to that section.
=> [Proposal] Add anchors to html report

include-build/roborazzi-core/src/androidMain/kotlin/com/github/takahirom/roborazzi/ViewScreenshot.kt
This PR updates the SDK warning message to recommend using API 28 or higher for proper functionality. This change addresses issues #114 and #164.
=> Update SDK Warning to API 28+

include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/CaptureResults.kt, include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziReportConst.kt
Once an image of the HTML report is clicked a bottom sheet modal is shown with that image.
In order to do that a imageBottomSheet is created in the html and then there is code in javascript that updates the modal content via javascript on image click.
Notice there is also a small unrelated change proposal of:
```
val imgAttributes = "style=\"width: 100%;...
```
for
```
val imgAttributes = "style=\"max-width: 100%;...
```
so that small images are not scaled up in the html report. If the original image was small (like a button) it was scaled up to match the width of the column table. No problem in reverting that but I think the report looks better if images are only scaled down or not scaled.
=> Show images in bottom sheet modal

include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt, include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt, include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt, sample-android/src/main/java/com/github/takahirom/roborazzi/sample/MainActivity.kt
=> Fix the bug where the test reports are not updated when the tests fail

README.md, roborazzi-painter/src/main/java/com/github/takahirom/roborazzi/DifferBufferedImage.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt, sample-android/src/main/java/com/github/takahirom/roborazzi/sample/FirstFragment.kt, sample-android/src/main/res/layout/fragment_first.xml, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ComposeSetContentTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ComposeTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ManualTest.kt
Fix https://github.com/takahirom/roborazzi/issues/207
=> Fix the issue where errors are ignored and occur when changing the size during GIF recording.

roborazzi-compose/src/main/java/com/github/takahirom/roborazzi/RoborazziCompose.kt
close https://github.com/takahirom/roborazzi/issues/227
This PR addresses a memory leak issue observed in our test cases. Previously, multiple instances of `captureRoboImage` calls were leading to an activity leak, potentially affecting the performance and reliability of our testing suite.
- Added `activityScenario.close()` in the relevant test cases. This ensures that each activity is properly closed after the test execution, preventing any memory leaks.
=> Add activityScenario.close() to prevent activity leak

.github/workflows/test.yaml, include-build/roborazzi-core/src/jvmTest/kotlin/io/github/takahirom/roborazzi/CaptureResultTest.kt
I checked to see if the Json conversion test was working correctly to tackle Issue #236 and found that it was not working correctly.
=> Fix CaptureResultTest and Add plan test workflow

gradle/libs.versions.toml, include-build/roborazzi-core/build.gradle, include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/CaptureResult.kt, include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/CaptureResults.kt, include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/ResultSummary.kt, include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt, include-build/roborazzi-core/src/jvmTest/kotlin/io/github/takahirom/roborazzi/CaptureResultTest.kt, include-build/roborazzi-gradle-plugin/build.gradle, include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt, include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt, roborazzi-compose-desktop/build.gradle, sample-android/src/main/java/com/github/takahirom/roborazzi/sample/MainActivity.kt
> - Using the org.json library requires manual mapping for each class, which is time-consuming.
> - Vulnerabilities in the org.json library appear frequently, making it difficult to maintain.
> - Since AGP also utilizes Gson, consolidating to a single library helps avoid the introduction of numerous libraries.
Migrate `org.json` to `Gson` for the above reasons
- Passed all `CaptureResultTest` tests
Fixed #236
=> refactor: migrating from the `org.json` Library to `Gson`

README.md, docs/topics/build_setup.md
Add build.gradle.kts example to the README to make Roborazzi setup easier.
Closes #229
=> doc: Add build.gradle.kts examples

include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/CaptureResult.kt, include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/CaptureResults.kt, include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt, include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziReportConst.kt, include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/processOutputImageAndReport.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ManualTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/boxed/ContextDataTest.kt
=> Add contextdata tabs to HTML report

include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt, include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt, include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt
close https://github.com/takahirom/roborazzi/issues/261
=> Fix Roborazzi output cache

include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/CaptureResults.kt
We can't see the HTML report because of Javascript error
```
Uncaught TypeError: Cannot read properties of null (reading 'length')
at l._setupActiveTabLink (materialize.min.js:6:115039)
at new l (materialize.min.js:6:113748)
at l.init (materialize.min.js:6:37127)
at l.init (materialize.min.js:6:113986)
at O.AutoInit (materialize.min.js:6:151127)
at index.html:5290:7
```
=> Add class="active" for anchor tag in HTML report

include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziTaskType.kt
Although using both 'compare' and 'verify' simultaneously is not supported, it may not be intuitive for the task to default to 'compare'. Therefore, I have configured it to prioritize 'verify'.
close https://github.com/takahirom/roborazzi/issues/268
=> Use 'verify' task when specifying both 'compare' and 'verify'

include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziContext.kt, include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt, include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziReportConst.kt, include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt, include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt, include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt
close https://github.com/takahirom/roborazzi/issues/265
=> Respect gradle build dir for reports

roborazzi/src/main/res/values/themes.xml
I tried out shadow rendering as outlined in #273 and noticed that there's a shadow from the top when using `captureRoboImage` with a composable parameter. This is visible in the diff for `manual_compose` in #273.
It seems that it's caused by the action bar of `RoborazziTransparentActivity` rendering right above the composable and thus "leaking" a shadow into the screenshot.
I tested the change by applying it on top of #273.
=> Hide action bar to avoid shadow creeping into images captured using captureRoboImage

gradle/libs.versions.toml
Enable Roborazzi to work in a Windows environment by increasing the robolectric version from 4.10.3 to 4.12.1
Fixes #288
=> update robolectric version from 4.10.3 to 4.12.1

include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt
Fixed typo in variable name.
`resutls` to `results`
=> fix typo in RoborazziGradleProject.kt

include-build/roborazzi-core/src/androidMain/kotlin/com/github/takahirom/roborazzi/capture.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ComposeTest.kt
This PR adds `Disabled: "true"` to the accessibility explanation when `SemanticsProperties.Disabled` is set (in Compose code).
I also included a test that includes UI elements for all the different semantic properties that are currently being printed.
We started using `Dump.AccessibilityExplanation` for a11y testing recently, and I noticed when working on Buttons that the output would be the same regardless of them being enabled or disabled. It made me wonder whether the `enabled` property was set correctly, so I thought it'd be good to reflect this in the test output.
=> Include Disabled semantic property in accessibility explanation

include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt, include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt
The reason we implemented cache invalidation was because our system lacked a proper mechanism for restoring caches, requiring us to clear them whenever the output directory was empty.
=> Remove unneeded cache invalidation

build.gradle, gradle/android.gradle, gradle/libs.versions.toml, include-build/build.gradle, include-build/roborazzi-core/build.gradle, include-build/roborazzi-gradle-plugin/build.gradle, include-build/roborazzi-gradle-plugin/src/integrationTest/projects/app/build.gradle.kts, roborazzi-compose-desktop/build.gradle, roborazzi-compose-ios/build.gradle, roborazzi-junit-rule/build.gradle, roborazzi-painter/build.gradle, sample-android-without-compose/build.gradle, sample-android/build.gradle
The source & target compatibility of all Roborazzi JAR/AAR artifacts remains at Java 11. This update to Java 17 could improve build speed a little, but primarily it paves the way towards matching the minimum Java version imposed by Android Gradle Plugin (since 8.0.0). Also, we will need to update to 17 eventually to address a failure we're seeing in [the `roborazzi-junit5` PR](https://github.com/takahirom/roborazzi/pull/355), which relies on an extension that was built against Java 17 internally.
Remove all usages of `JavaVersion.VERSION_11` and move them into the central `build.gradle` build script. Unfortunately, this still needs to be duplicated for the `include-build` projects, but at least those can use the same version definitions from the version catalog.
=> Update toolchain to Java 17 for all modules

renovate.json
As the title says.
Removed `io.github.takahirom.roborazzi` dependency from Renovate watching list using `ignoreDeps`.
Fixed #371
=> Exclude `io.github.takahirom.roborazzi` dependency from Renovate updates

include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt
I sometimes get this error:
```
* What went wrong:
A problem was found with the configuration of task ':sample-android:testDebugUnitTest' (type 'AndroidUnitTest').
- Type 'com.android.build.gradle.tasks.factory.AndroidUnitTest' property '$1' specifies directory '/Users/lukas/Dev/test/roborazzi/sample-android/build/outputs/roborazzi' which doesn't exist.
Reason: An input file was expected to be present but it doesn't exist.
Possible solutions:
1. Make sure the directory exists before the task is called.
2. Make sure that the task which produces the directory is declared as an input.
For more information, please refer to https://docs.gradle.org/8.4/userguide/validation_problems.html#input_file_does_not_exist in the Gradle documentation.
```
It's a bit hard to reproduce, since I believe the …
=> Declare input directories as files to avoid issues when they don't exist

include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt
It seems that the task information provided by TestTaskSkipEventsServiceProvider, which is necessary to decide whether we should restore the cache to the output directory, isn't saved correctly. Therefore, I removed TestTaskSkipEventsServiceProvider and now always restore the cache. The performance impact appears to be minimal, and consistency is more important.
=> Fix output image consistency issue

include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt, include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt, include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt
The challenges we aim to address
https://github.com/takahirom/roborazzi/pull/386
> Problem
Currently, Roborazzi's gradle plugin declares the output directory (where the golden screenshot files are stored) as an input. This is correct when the task runs in compare and verify modes, but it is not necessary when running record mode only.
The side-effect of this is that it is much more difficult to find an existing build cache entry.
=> Use empty files for record task

README.md, docs/topics/faq.md
=> Add faq section about out of memory error

include-build/roborazzi-gradle-plugin/build.gradle, include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/WebAssets.kt, include-build/roborazzi-gradle-plugin/src/test/java/io/github/takahirom/roborazzi/WebAssetsTest.kt
Follow up to #404.
Add missing unit test for `WebAssets` class
=> Add unit test for WebAssets class

include-build/roborazzi-core/src/androidMain/kotlin/com/github/takahirom/roborazzi/capture.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ComposeTest.kt
When dumping accessibility texts, I noticed that we either included content description or text.
However, it seems like when you merge e.g. an `Icon` with a content description and a `Text` field, both of them are included. So for those cases, only the content description would be included in our regression tests.
Note: I didn't include the same fix for the legacy view system, since I'm not sure if it also applies there.
=> Dump both content description as well as text for the case when two elements are merged

docs/topics/idea_plugin.md, roborazzi-idea-plugin/build.gradle.kts, roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/PreviewViewModel.kt, roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/RoborazziGradleTask.kt, roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/RoborazziPreviewTool.kt, roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/StatusToolbarPanel.kt
Fixes #424 
- Add a dropdown menu to a toolbar for selecting task to run
Initial implementation to solicit early feedback...
=> Generate Roborazzi images via its IntelliJ Plugin

include-build/roborazzi-core/src/commonMain/kotlin/com/github/takahirom/roborazzi/RoborazziTaskType.kt, roborazzi-idea-plugin/build.gradle.kts, roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/PreviewViewModel.kt, roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/RoborazziGradleTask.kt, roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/RoborazziPreviewTool.kt, roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/StatusToolbarPanel.kt
* Roborazzi Plugin will use default configuration of IDE
* Sort Gradle tasks and select first by default
https://github.com/user-attachments/assets/76559bf1-3d90-4a93-9bb5-ab708e01de17
=> Adjust some idea plugin behaviors

roborazzi-idea-plugin/build.gradle.kts, roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/RoborazziPreviewTool.kt, roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/TaskToolbarPanel.kt
The Gradle tasks used to shrink like this:
We move the status label to the bottom
=> Tweak idea plugin UI

roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/TaskToolbarPanel.kt
Fixes #450.
Before | After
:--: | :--:
||<img src="https://github.com/user-attachments/assets/eecedf05-ff64-49f2-be1e-a3fb14ceecb5" width="300" alt="Screenshot showing dropdown of Gradle tasks - indicating that there is no regression" />
=> Hide dropdown border if no gradle tasks exists

roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/TaskToolbarPanel.kt
Fixes #454 
- Remove anchoring of the JBBox harboring the toolbar to `BorderLayout.WEST` as it causing the user to resize the window to reveal it fully.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/18d34773-0b79-4c30-834b-da03d84b6c3e" width="300" alt="Screen recording showing issue with toolbar dropdown hiding and requiring a window resize" /> | <video src="https://github.com/user-attachments/assets/b0732be7-be97-4ae7-a44e-b6aa89619603" width="300" alt="Screen recording showing the issue fixed where the toolbar dropdown doesn't require window resizing" />
=> Don't crop dropdown task run button

roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/RoborazziPreviewTool.kt
Close #466 
- Get the maximum number of characters of text that will fit in the screen width with a binary search, split the string, and concatenate them with `<br>` tag.
- May be slightly inaccurate.
https://github.com/user-attachments/assets/17354551-8382-4e9f-b69d-8a3111fd3978
=> Show screenshot filename multiple lines

roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/PreviewViewModel.kt, roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/RoborazziPreviewTool.kt
Installed TextField to allow narrowing down the image in the displayed screenshot.
The location of the text field is tentative, so if you have a request, please let me know where you would like to place it.
Fixed #475 
https://github.com/user-attachments/assets/ccda4660-2ca3-489b-8a1e-babb779806bc
=> Filtering Images by Text Field

include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/processOutputImageAndReport.kt, include-build/roborazzi-core/src/commonMain/kotlin/com/github/takahirom/roborazzi/CaptureResult.kt, include-build/roborazzi-core/src/jvmTest/kotlin/io/github/takahirom/roborazzi/CaptureResultTest.kt, roborazzi-compose-ios/src/iosMain/kotlin/io/github/takahirom/roborazzi/RoborazziIos.kt
**This PR is my proposed solution for #460.**
Please take a look at the way I implemented the property `diffPercentage` in the `CaptureResult.Changed` data class. Another possibility would be to declare `diffPercentage` directly as a property in the `CaptureResult` interface, and implement them as null-returning-getters in the other data classes, as you have done for other properties. (This would also remove the need for my if-statement in `CaptureResultTest.kt`.)
Also, as far as I can tell, you plan to use the Dropbox Differ in the future for iOS as well (see [this](https://github.com/takahirom/roborazzi/blob/1924d408d2e99e1d9e65a557d7f3711fa9368367/roborazzi-compose-ios/src/iosMain/kotlin/io/github/takahirom/roborazzi/RoborazziIos.kt#L366) comment). That's why I have implemented the …
=> Implement diff. percentage

roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/PreviewViewModel.kt
For example, let's say there are the following functions in the file: `ExampleChip` and `ExampleChipPreview`. In the current implementation, `ExampleChip` is also included in `ExampleChipPreview`, resulting in the same preview being displayed twice. To avoid this, I added a process to delete duplicate files.
https://github.com/takahirom/roborazzi/blob/fe9d08a77197055138c58189ccd21764363c9e4a/roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/PreviewViewModel.kt#L263-L280
I am not very good at English, so I am using ChatGPT.
=> fix duplicate screenshot

roborazzi-ai-openai/src/commonMain/kotlin/com/github/takahirom/roborazzi/OpenAiRoborazziAi.kt
Although max_tokens has been deprecated, we still need to use it in certain environments.
=> Use max_tokens instead of max_completion_tokens

roborazzi-accessibility-check/src/main/java/com/github/takahirom/roborazzi/RoborazziATFAccessibilityChecker.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ComposeA11yTest.kt
Add tests showing we don't fail when configured incorrectly, and log if not in NATIVE mode.
relates to https://github.com/takahirom/roborazzi/issues/569
=> Log warnings when Accessibility checks not configured correctly

roborazzi-accessibility-check/src/main/java/com/github/takahirom/roborazzi/RoborazziATFAccessibilityChecker.kt
Restores the original Robolectric fingerprint after performing accessibility checks. This ensures that the fingerprint is not permanently modified, which can cause issues in other parts of the test suite.
=> Fix: Restore Robolectric fingerprint after accessibility checks

roborazzi-accessibility-check/src/main/java/com/github/takahirom/roborazzi/RoborazziATFAccessibilityChecker.kt
This change introduces a new `applySuppressions` function to process suppressions for accessibility check results. It filters results based on suppression rules and adds a new `AccessibilityCheckResultType.SUPPRESSED` type for suppressed results. Additionally, it adds logging for suppressed results.
Existing logic filters instead of suppressing, making these invisible.
fixes #570
=> Apply suppressions to AccessibilityViewCheckResult instead of filtering

build.gradle, include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt, include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/GenerateComposePreviewRobolectricTestsExtension.kt, roborazzi-junit-rule/src/main/java/com/github/takahirom/roborazzi/RoborazziRule.kt, roborazzi-painter/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/AnimatedGifEncoder.kt, roborazzi-painter/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/AwtRoboCanvas.kt, roborazzi/src/main/java/com/github/takahirom/roborazzi/captureDump.kt, roborazzi/src/test/java/com/github/takahirom/roborazzi/Devices.kt, roborazzi/src/test/java/com/github/takahirom/roborazzi/GenerateQualifiersTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ComparisonStyleTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ComposeA11yTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ComposeA11yWithCustomCheckTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/GeminiAiAiTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ManualTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/OpenAiTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/RuleTestWithPath.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ViewA11yTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/WindowCaptureTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/boxed/AiManualTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/boxed/ContextDataTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/boxed/FilePathTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/boxed/LosslessWebpTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/boxed/RoborazziTaskTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/boxed/SizeChangeTest.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/boxed/boxedEnvironment.kt
* Separated the constructor to isolate stable parameters.
https://github.com/takahirom/roborazzi/issues/565#issuecomment-2492768446
* Sample modules now do not suppress opt-in requirements by default to highlight experimental exposure issues.
* Enabled `allWarningsAsErrors = true` to detect experimental annotation exposure during development.
=> Fix the issue where the experimental annotation was exposed when using stable APIs in Roborazzi options

include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt, include-build/roborazzi-core/src/commonMain/kotlin/com/github/takahirom/roborazzi/RoborazziProperties.kt, include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt, include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt, include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt
Previously, when modifying `roborazzi.outputDir`, such as setting it to `src/screenshots`, this option also affected the paths for comparison images, like `foo_compare.png`. This behavior often caused issues, such as unintentionally saving comparison images to version control systems (e.g., Git). To address this, we have discontinued this behavior. Comparison images are now saved in `build/outputs/roborazzi` by default, while the behavior for reference images remains unchanged.
For users who wish to customize the path for comparison images, we have introduced a new option: `roborazzi.compare.outputDir`.
While I don't believe there are strong use cases for this, if you want to save the comparison images in a custom directory as you did before, you can specify `roborazzi.compare.outputDir` …
=> Add roborazzi.compare.output.dir gradle.properties

include-build/roborazzi-core/src/androidMain/kotlin/com/github/takahirom/roborazzi/ComposePrintToString.kt
Dump screenshot has node properties. Sometime Roborazzi generates new screenshots (or fails verification) due the node properties order. This Pull Request add the output sorting to avoid the issue.
=> Sort units and actions of ComposePrintToString to stabilize output in Dump screenshots.

roborazzi-compose/src/main/java/com/github/takahirom/roborazzi/RoborazziComposeOptions.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ManualTest.kt
=> add localInspectionMode property to RoborazziComposeOptions

include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt, include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt
=> Removing files from intermediate dir to prevent old screenshots from reappearing

include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt
Sort capture results by the file path of their golden image, achieving a deterministic order of screenshots that groups together related images.
|Before|After|
|---|---|
|<img width="500" alt="Screenshot 2024-12-27 at 12 09 29" src="https://github.com/user-attachments/assets/0f500f3f-4e56-4501-aaac-69eb4edd0ef1" />|<img width="500" alt="Screenshot 2024-12-27 at 12 10 47" src="https://github.com/user-attachments/assets/60bdfed7-b71f-432a-980f-0907f19922df" />|
Resolves #621.
=> Sort capture results to achieve deterministic order in HTML report

roborazzi-ai-openai/src/commonMain/kotlin/com/github/takahirom/roborazzi/OpenAiAiAssertionModel.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/GeminiWithOpenAiApiInterfaceTest.kt
To support this https://github.com/takahirom/arbigent/pull/8
=> Make OpenAiAiAssertionModel gemini API compatible

include-build/roborazzi-core/src/androidMain/kotlin/com/github/takahirom/roborazzi/ComposePrintToString.kt, sample-android/src/test/java/com/github/takahirom/roborazzi/sample/ComposeLambdaTest.kt
Dump screenshot has node properties. Sometime Roborazzi generates new screenshots (or fails verification) due the node print the `androidx.compose.ui.semantics.CollectionInfo` reference value instead of content. This Pull Request add the output sorting to avoid the issue.
=> Print collection content in ComposePrintToString to stabilize output in Dump screenshots.

include-build/roborazzi-core/src/commonMain/kotlin/com/github/takahirom/roborazzi/CaptureResult.kt, include-build/roborazzi-core/src/commonMain/kotlin/com/github/takahirom/roborazzi/CaptureResults.kt, include-build/roborazzi-gradle-plugin/src/main/resources/META-INF/assets/report-style.css
This is a proposal to adjust the layout of Roborazzi reports a little, addressing some quirks I have found when working with it. Left is before, right is after!
I adjusted the default width of the report container to account for larger screens. Instead of materialize's default values (90%, max 1280px), it is now 95% with a maximum width of 1440px. Furthermore, the ratio between the left and right columns is now 40-60, a little different to the 30-70 from before. I also added a little fix for contextData: Before this PR, if any contextData has an empty value, then _no_ context data would be shown at all. This is now changed so that only these empty context data entries are filtered out instead.
This accounts for use cases where a non-default directory is used to store images. The folder is …
=> Update formatting of left column in reports

roborazzi-painter/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/AwtRoboCanvas.kt
=> Handle font availability errors by catching Throwable

gradle.properties, roborazzi-compose-preview-scanner-support/src/main/java/com/github/takahirom/roborazzi/RoborazziPreviewScannerSupport.kt, roborazzi-compose/src/main/java/com/github/takahirom/roborazzi/RoborazziComposeOptions.kt
It seems that calling `org.robolectric.RuntimeEnvironment.setQualifiers()` takes some time.
=> Improve compose config performance for Compose Preview Support

README.md, docs/topics/preview_support.md
I found the existing documentation for using Groovy DSL instead of Kotlin DSL confusing. This is one minor change applied to two different locations, with clearer wording and the second example included since these conversions can be non-obvious.
=> Minor tweak to documentation for Groovy DSL

README.md, docs/topics/preview_support.md, proposals/01-make-AndroidComposePreviewTester-customizable.md, roborazzi-compose-preview-scanner-support/src/main/java/com/github/takahirom/roborazzi/RoborazziPreviewScannerSupport.kt
Add a Capturer interface to AndroidComposePreviewTester to enable customization of screenshot capture behavior.
Addresses Issue #703 - Users requested the ability to set custom changeThreshold for generated Compose preview tests. The composition-based solution allows users to customize capture behavior while maintaining backward compatibility.
=> Add Capturer interface for customizing AndroidComposePreviewTester

.github/workflows/CompareScreenshot.yml, .github/workflows/StoreScreenshot.yml
Increase timeout for screenshot CI workflows from 30 to 50 minutes
Workflows are timing out before completion, preventing profile reports from being generated
=> Increase CI timeout to 50 minutes
